/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { ArrowLeft, Eye, Save } from "lucide-react";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { money } from "@/lib/utils";
import { configuredAutomaticPrice } from "@/lib/pricing";
import { saveCatalogStatus, saveCommercialStatus, saveImageStrategy, saveManualPrice } from "@/app/admin/actions";
import { AdminProductImageUpload } from "@/components/admin-product-image-upload";

export default async function EditProduct({params}:{params:Promise<{id:string}>}) {
  const {id}=await params;
  const supabase=await createClient();
  const [{data:p},{data:standardTiers},{data:accessoryTiers},{data:costs}]=await Promise.all([supabase.from("products").select("*,brand:brands(name),category:categories(name,pricing_mode),product_variants(*,supplier_offers(cost,available,supplier:suppliers(code,name)))").eq("id",id).single(),supabase.from("pricing_tiers").select("*").eq("active",true).order("sort_order"),supabase.from("accessory_pricing_tiers").select("*").eq("active",true).order("sort_order"),supabase.from("operational_costs").select("*").single()]);
  if(!p)notFound();

  return <>
    <div className="admin-heading"><div><Link className="back-link" href="/admin/produtos"><ArrowLeft/> Produtos</Link><h1>{p.name}</h1><p>{p.brand?.name} · {p.category?.name} · {p.condition}</p></div><a className="admin-outline" href={`/produto/${p.slug}`} target="_blank"><Eye/> Visualizar como cliente</a></div>
    <section className="admin-card"><div className="card-title"><strong>Informações básicas</strong></div><div className="detail-grid"><div><span>Modelo</span><strong>{p.model}</strong></div><div><span>Conectividade</span><strong>{p.connectivity||"Não informado"}</strong></div><div><span>Condição</span><strong>{p.condition}</strong></div><div><span>Publicação</span><strong>{p.catalog_status==="ready"?"QA aprovado":"Rascunho"}</strong></div></div><form action={saveCatalogStatus} className="price-form catalog-status-form"><input type="hidden" name="product_id" value={p.id}/><label>Status do catálogo<select name="catalog_status" defaultValue={p.catalog_status??"draft"}><option value="draft">Rascunho — oculto da vitrine</option><option value="ready">QA aprovado — pode aparecer</option></select></label><button type="submit"><Save/> Salvar status</button></form><form action={saveCommercialStatus} className="price-form catalog-status-form"><input type="hidden" name="product_id" value={p.id}/><label>Situação comercial<select name="commercial_status" defaultValue={p.commercial_status??"available"}><option value="available">Disponível</option><option value="coming_soon">Em breve</option><option value="restocking">Aguardando reposição</option></select></label><button type="submit"><Save/> Salvar situação</button></form></section>
    <section className="admin-card"><div className="card-title"><strong>Padrão das imagens por cor</strong><small>A capa da vitrine é independente da galeria e pode reunir as cores comerciais.</small></div><form action={saveImageStrategy} className="price-form"><input type="hidden" name="product_id" value={p.id}/><label>Estratégia visual<select name="image_strategy" defaultValue={p.image_strategy??"variant"}><option value="variant">Uma imagem própria para cada cor</option><option value="group">Uma foto coletiva mostra todas as cores</option></select></label><label>Capa da vitrine<input name="storefront_image" defaultValue={p.storefront_image??""} placeholder="/products/capa-multicolor.webp"/></label><button type="submit"><Save/> Salvar padrão</button></form></section>
    <section className="admin-card">
      <div className="card-title"><strong>Variantes e preços</strong><small>Preço manual nunca é sobrescrito por atualização de custo.</small></div>
      <div className="variant-admin-list">{p.product_variants.map((v:any)=>{
        const offers=v.supplier_offers.filter((o:any)=>o.available).sort((a:any,b:any)=>Number(a.cost)-Number(b.cost));
        const cost=Number(offers[0]?.cost??0);const mode=(p.category?.pricing_mode??"standard") as "standard"|"accessory";const auto=configuredAutomaticPrice(cost,mode,standardTiers??[],accessoryTiers??[]);const current=Number(v.manual_price??auto);const commission=Number(costs?.seller_commission_percent??.01);const operational=Number(costs?.delivery_cost??15)+Number(costs?.packaging_cost??1);const result=current-cost-current*commission-operational;
        return <form action={saveManualPrice} key={v.id} className="variant-admin-card">
          <input type="hidden" name="variant_id" value={v.id}/>
          <div className="variant-admin-head"><div><strong>{[v.ram_gb?`${v.ram_gb} GB RAM`:null,v.storage_gb?`${v.storage_gb} GB`:null,v.color].filter(Boolean).join(" · ")}</strong><small>{v.sku}{v.condition_grade?` · ${v.condition_grade.replace("_"," ")}`:""}</small></div><span className={v.manual_price?"manual-tag":"status on"}>{v.manual_price?"Preço manual":"Automático"}</span></div>
          <div className="finance-preview"><div><span>Custo atual</span><strong>{money.format(cost)}</strong></div><div><span>Preço automático</span><strong>{money.format(auto)}</strong></div><div><span>Comissão {(commission*100).toLocaleString("pt-BR")}%</span><strong>{money.format(current*commission)}</strong></div><div><span>Entrega + embalagem</span><strong>{money.format(operational)}</strong></div><div className="result"><span>Resultado estimado</span><strong>{money.format(result)}</strong></div></div>
          {v.color&&<div className="variant-color-admin"><label>Cor comercial<input name="color" defaultValue={v.color}/></label><label>Código visual da cor<input name="color_hex" type="color" defaultValue={v.color_hex??"#aaa39a"}/></label><label>Imagem desta cor<input name="image_url" defaultValue={v.images?.[0]??""} placeholder="/products/modelo-cor.webp"/></label></div>}
          <AdminProductImageUpload variantId={v.id} currentImage={v.images?.[0]??null} canApplyToEquivalentVariants={Boolean(v.color)}/>
          {p.condition==="seminovo"&&<fieldset className="used-admin-settings"><legend>Condição do seminovo</legend><p>O padrão é Excelente. Altere somente quando esta unidade for uma exceção.</p><div><label>Classificação<select name="condition_grade" defaultValue={v.condition_grade??"excelente"}><option value="excelente">Excelente</option><option value="muito_bom">Muito bom</option><option value="bom">Bom</option></select></label><label>Bateria mínima (%)<input name="battery_health_minimum" type="number" min="1" max="100" defaultValue={v.battery_health_minimum??85}/></label><label>Componentes 100% originais?<select name="original_components" defaultValue={String(v.original_components??true)}><option value="true">Sim</option><option value="false">Não</option></select></label><label>Nunca foi aberto?<select name="never_opened" defaultValue={String(v.never_opened??true)}><option value="true">Sim</option><option value="false">Não</option></select></label><label>Garantia Super Cell (meses)<input name="warranty_months" type="number" min="0" max="60" defaultValue={v.warranty_months??3}/></label><label>Observações da condição<input name="condition_details" maxLength={500} defaultValue={v.condition_details??""} placeholder="Ex.: tela substituída, marcas na lateral..."/></label></div></fieldset>}
          <div className="price-form"><label>Regra de preço<select name="mode" defaultValue={v.manual_price?"manual":"automatic"}><option value="automatic">Usar preço automático</option><option value="manual">Substituir preço automático</option></select></label><label>Novo preço Pix<input name="manual_price" type="number" min="0" step="0.01" defaultValue={v.manual_price??auto}/></label><label>Motivo<select name="reason" defaultValue={v.manual_price_reason??""}><option value="">Sem motivo</option><option>Promoção</option><option>Preço de mercado</option><option>Queima de estoque</option><option>Ação comercial</option><option>Outro</option></select></label><button type="submit"><Save/> Salvar alterações</button></div>
          <details><summary>Ofertas internas ({offers.length})</summary>{offers.map((o:any)=><p key={`${o.supplier.code}-${o.cost}`}>{o.supplier.code} · {o.supplier.name} — {money.format(Number(o.cost))}</p>)}</details>
        </form>;
      })}</div>
    </section>
  </>;
}
