-- SUPERSEDED / DO NOT APPLY
--
-- The original 2026-10-06 Guanacel snapshot in this file contained only 20 of the
-- 29 live supplier offers and used a Preview overlay approach that was later removed.
--
-- The authoritative catalog sync was applied directly to the Super Cell Supabase
-- project as migration:
--   sync_full_guanacel_catalog_20261006_v3
--
-- That sync:
-- - imports all 29 live F1-A offers captured from GUANACELL08 on 2026-10-06;
-- - preserves existing product/variant images and manual refinements;
-- - preserves F1-B / used-iPhone offers;
-- - creates missing products/variants only;
-- - deactivates stale variants only when no supplier has an active offer;
-- - keeps Supabase as the single catalog source.
--
-- This historical file is intentionally a no-op to prevent the incomplete snapshot
-- from being applied in a future environment.
