import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Header } from "@/components/header";
import { ProductExperience } from "@/components/product-experience";
import { SiteFooter } from "@/components/site-footer";
import { FloatingWhatsApp } from "@/components/floating-whatsapp";
import { getCommerceData, getProduct } from "@/lib/data";
import { money, productDisplayName } from "@/lib/utils";
export const revalidate=60;
export async function generateMetadata({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{variante?:string}>}):Promise<Metadata>{const [{slug},{variante}]=await Promise.all([params,searchParams]);const items=await getProduct(slug);if(!items.length)return{};const product=items.find((item)=>item.variant_id===variante)??items[0];const displayName=productDisplayName(product);const config=[product.ram_gb?`${product.ram_gb} GB RAM`:null,product.storage_gb?`${product.storage_gb} GB`:null,product.color??null].filter(Boolean).join(" · ");const price=product.price_pix!==null?`${money.format(Number(product.price_pix))} no Pix`:null;const description=[config,price,"até 18x","pagamento somente na entrega"].filter(Boolean).join(" · ");const image=product.storefront_image??product.images?.[0]??null;const productUrl=`https://catalogo.supercellrn.com/produto/${slug}${variante?`?variante=${encodeURIComponent(variante)}`:""}`;return{title:displayName,description,alternates:{canonical:productUrl},openGraph:{title:`${displayName} | Super Cell`,description,url:productUrl,type:"website",siteName:"Super Cell",images:image?[{url:image,alt:displayName}]:[]},twitter:{card:"summary_large_image",title:`${displayName} | Super Cell`,description,images:image?[image]:[]}}}
export default async function ProductPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{variante?:string}>}){const [{slug},{variante}]=await Promise.all([params,searchParams]);const [variants,commerce]=await Promise.all([getProduct(slug),getCommerceData()]);if(!variants.length)notFound();const selectedVariant=variants.find((item)=>item.variant_id===variante)??variants[0];const storefrontVariants=[selectedVariant];const instagramUrl=String(commerce.settings.instagram_url??"").trim();const whatsapp=String(commerce.settings.whatsapp_sales??"");const cnpj=String(commerce.settings.company_cnpj??"").trim();const location=String(commerce.settings.company_location??"Natal, Rio Grande do Norte").trim();const config=[selectedVariant.ram_gb?`${selectedVariant.ram_gb} GB RAM`:null,selectedVariant.storage_gb?`${selectedVariant.storage_gb} GB`:null].filter(Boolean).join(" + ");const floatingMessage=`Olá! Vim pelo catálogo da Super Cell e estou vendo o ${selectedVariant.product_name}${selectedVariant.color?` — ${selectedVariant.color}`:""}${config?` — ${config}`:""}. Gostaria de tirar uma dúvida sobre este aparelho.`;return <main><Header instagramUrl={instagramUrl||undefined}/><ProductExperience variants={storefrontVariants} initialVariantId={selectedVariant.variant_id} acquirer={commerce.acquirer} schedules={commerce.schedules} exceptions={commerce.exceptions} whatsapp={whatsapp} cashText={String(commerce.settings.cash_on_delivery_text??"Pagamento somente na entrega.")} accessoryDeliveryFee={Number(commerce.settings.accessory_delivery_fee??15)} accessoryFreeThreshold={Number(commerce.settings.accessory_free_delivery_threshold??100)}/><SiteFooter whatsapp={whatsapp} cnpj={cnpj||undefined} location={location}/><FloatingWhatsApp number={whatsapp} message={floatingMessage}/></main>}
