import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Header } from "@/components/header";
import { ProductExperience } from "@/components/product-experience";
import { SiteFooter } from "@/components/site-footer";
import { getCommerceData, getProduct } from "@/lib/data";
import { productDisplayName } from "@/lib/utils";
export const revalidate=60;
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const items=await getProduct(slug);if(!items.length)return{};const product=items[0];const displayName=productDisplayName(product);return{title:displayName,description:product.description??`Veja preço, parcelamento e disponibilidade do ${displayName}.`,openGraph:{title:`${displayName} | Super Cell`,description:product.description??"Veja condições e faça seu pedido.",images:product.images?.[0]?[{url:product.images[0]}]:[]}}}
export default async function ProductPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{variante?:string}>}){const [{slug},{variante}]=await Promise.all([params,searchParams]);const [variants,commerce]=await Promise.all([getProduct(slug),getCommerceData()]);if(!variants.length)notFound();const instagramUrl=String(commerce.settings.instagram_url??"").trim();const whatsapp=String(commerce.settings.whatsapp_sales??"");const cnpj=String(commerce.settings.company_cnpj??"").trim();const location=String(commerce.settings.company_location??"Natal, Rio Grande do Norte").trim();return <main><Header instagramUrl={instagramUrl||undefined}/><ProductExperience variants={variants} initialVariantId={variante} acquirer={commerce.acquirer} schedules={commerce.schedules} exceptions={commerce.exceptions} whatsapp={whatsapp} cashText={String(commerce.settings.cash_on_delivery_text??"Pagamento somente na entrega.")} accessoryDeliveryFee={Number(commerce.settings.accessory_delivery_fee??15)} accessoryFreeThreshold={Number(commerce.settings.accessory_free_delivery_threshold??100)}/><SiteFooter whatsapp={whatsapp} cnpj={cnpj||undefined} location={location}/></main>}
